//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proYP04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.История_входа = new HashSet<История_входа>();
        }
    
        public int Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Серия_и_номер { get; set; }
        public string Фото { get; set; }
        public string Номер_телефона { get; set; }
        public string Email { get; set; }
        public Nullable<int> Должность { get; set; }
        public string Логин { get; set; }
        public Nullable<int> Подразделение { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
    
        public virtual Должность Должность1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_входа> История_входа { get; set; }
        public virtual Подразделение Подразделение1 { get; set; }
        public virtual Права_доступа Права_доступа { get; set; }
    }
}
