//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proYP04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары_в_заказе
    {
        public int Код { get; set; }
        public Nullable<int> Товар { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<double> Стоимость { get; set; }
        public Nullable<int> Заказ { get; set; }
    
        public virtual Заказ Заказ1 { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
