//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proYP04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Товары_в_заказе = new HashSet<Товары_в_заказе>();
            this.Товары_в_корзине = new HashSet<Товары_в_корзине>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Категория { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Картинка { get; set; }
        public Nullable<int> Остаток_товара { get; set; }
    
        public virtual Категории_товаров Категории_товаров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товары_в_заказе> Товары_в_заказе { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товары_в_корзине> Товары_в_корзине { get; set; }
    }
}
